#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <stack>
#include <queue>
#include <cmath>
#include <unordered_map>
#include <unordered_set>
#include <limits>
#include <climits>
#include <cstring>
#include <set>
#include <cstring>
#include <numeric>